apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2368"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368
    name: http
  type: LoadBalancer