apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ghost-monitor
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  endpoints:
  - port: http
    path: /metrics