global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'ghost'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      target_label: __port__
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.43.189:9100']