pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t ghost-local:latest ./src/'
      }
    }
    stage('Test') {
      steps {
        sh './scripts/test.sh'
      }
    }
    stage('Deploy') {
      steps {
        sh 'docker tag ghost-local:latest 192.168.43.189:5000/ghost-local:latest'
        sh 'docker push 192.168.43.189:5000/ghost-local:latest'
        sh './scripts/deploy.sh'
      }
    }
  }
}